### ISSUE TITLE
 excessive repetition */n minute job

### ISSUE THREAD

**Issue by proekt111** [zalando/elephant-worker#10]
Let's define job for every 3 minutes from 6am till 11pm monday to friday.

SELECT *
  FROM scheduler.insert_job(job_command := 'select scheduler.test_job();',
                  datname     := 'testdb',
                  schedule    := '*/3 6-23 * * 1-5 +03',
                  job_description := 'test 003'
                 );
For such job
(scheduler.parse_crontab('*/3 6-23 * * 1-5 +03')).minute return {0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57} minutes array

The function job_scheduled_at return job multiple times at any minutes in  array.

Examples
    SELECT job.*,
           datname,
           rolname
      FROM scheduler.job
      JOIN pg_catalog.pg_roles    pr ON (job.roloid = pr.oid)
      JOIN pg_catalog.pg_database pd ON (job.datoid = pd.oid)
     WHERE pg_has_role(session_user, roloid, 'MEMBER')
       AND (scheduler.parse_crontab(schedule)).minute @> ARRAY[extract(minute from '2015-09-01 15:42:18.881769+03'::timestamptz)::int]
       AND (scheduler.parse_crontab(schedule)).hour   @> ARRAY[extract(hour   from '2015-09-01 15:42:18.881769+03'::timestamptz)::int]
       AND (scheduler.parse_crontab(schedule)).month  @> ARRAY[extract(month  from '2015-09-01 15:42:18.881769+03'::timestamptz)::int]
       AND (
                (scheduler.parse_crontab(schedule)).dom @> ARRAY[extract(dow    from '2015-09-01 15:42:18.881769+03'::timestamptz)::int]
                OR
                (scheduler.parse_crontab(schedule)).dow @> ARRAY[extract(dow    from '2015-09-01 15:42:18.881769+03'::timestamptz)::int]
           )
       AND enabled = true

**Comment by proekt111** [comment]
Lost asterisk in shedule definition
"/3 6-23 * * 1-5 MSK" -> "*/3 6-23 * * 1-5 MSK"

**Comment by alexeyklyukin** [comment]
Do you have only one definition of this job in the scheduler.job table?

**Comment by proekt111** [comment]
Yes. Only  one job in scheduler.my_job. 
I uninstall extension, drop schema cascade, restart cluster, recreate all stuff and repeat this.

**Comment by proekt111** [comment]
Should  the function  job_scheduled_at be called ones a minute in my case?

**Comment by alexeyklyukin** [comment]
I think it should be every once in 3 minutes, as the schedule dictates. If it's not the case - it's, likely, a bug.

**Comment by feikesteenbergen** [comment]
/3 is not a valid crontab syntax, the function was wrong to continue, it now raises an exception when the crontab entry does not match the defined regular expressino.
