### ISSUE TITLE
lots of compilation warning

### ISSUE THREAD

**Issue by ker2x** [zalando/elephant-worker#5]
Friendly greetings \o/

There is a lot of easy-to-fix compilation warning.
Do you want to fix them yourself in a near future or do you accept the easy-patchs to fix them ? :)

**Comment by alexeyklyukin** [comment]
Hi,

The C part is WIP and would not work without further efforts put into it,
so I wouldn't waste time fixing compiler warnings at the moment.

On Wednesday, May 6, 2015, Laurent Laborde <notifications@github.com> wrote:

> Friendly greetings \o/
>
> There is a lot of easy-to-fix compilation warning.
> Do you want to fix them yourself in a near future or do you accept the
> easy-patchs to fix them ? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zalando/elephant-worker/issues/5>.
>


-- 
--
Oleksii Kliukin
Database Engineer

**Comment by ker2x** [comment]
ok thx :)
