### ISSUE TITLE
Job Queue possible extension

### ISSUE THREAD

**Issue by qooleot** [zalando/elephant-worker#7]
Hey, I've been working on a postgres job queue, and was about to get to background workers - and ran across your repo.  One quick question - what license are you applying to this code?

**Comment by hjacobs** [comment]
@feikesteenbergen or @alexeyklyukin might answer this question --- I assume it will be Apache 2.0 :-)

**Comment by alexeyklyukin** [comment]
Yes, it's Apache 2.0
