### ISSUE TITLE
background worker doesn't start

### ISSUE THREAD

**Issue by proekt111** [zalando/elephant-worker#9]
CREATE SCHEMA scheduler;
CREATE EXTENSION elephant_worker WITH SCHEMA scheduler;

#grep shared_preload_libraries /etc/postgresql/9.4/main/postgresql.conf
shared_preload_libraries = ''pg_stat_statements,pg_stat_kcache,elephant_worker'

#ls -l /usr/lib/postgresql/9.4/lib/elephant_worker.so
-rw-r--r-- 1 root root 65447 Aug 31 17:21 /usr/lib/postgresql/9.4/lib/elephant_worker.so

When cluster restart:
3659 LOG: registering background worker "elephant launcher"
3660 LOG: database system was shut down at 2015-08-31 17:23:36 MSK
3660 LOG: MultiXact member wraparound protections are now enabled
3659 LOG: starting background worker process "elephant launcher"
3659 LOG: database system is ready to accept connections
3664 LOG: autovacuum launcher started
3666 FATAL: could not query system catalogs for extension elephant_worker
3659 LOG: worker process: elephant launcher (PID 3666) exited with exit code 1
3659 LOG: unregistering background worker "elephant launcher"

**Comment by alexeyklyukin** [comment]
Did you point elephant_worker.database in postgresql.conf to the database name you've installed the extension to?

**Comment by proekt111** [comment]
No i d'nt. How to point db name in postgresql.conf ?

**Comment by alexeyklyukin** [comment]
In your postgresql.conf, set
elephant_worker.database = 'db_where_extension_is_installed'.

**Comment by proekt111** [comment]
that's work, thank you!
